//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "keywords")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub title: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_keywords::Entity")]
    UserKeywords,
}

impl Related<super::user_keywords::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserKeywords.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_keywords::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_keywords::Relation::Keywords.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
